on:
  push:
    branches:
      - master

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  build:
    name: Build
    runs-on: [ubuntu-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: 2

      - name: Go Test
        run: go test -v

      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: random
          SLACK_TITLE: [bitflyergo] Test is successful
          SLACK_COLOR: good

      - name: Slack Notification on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: random
          SLACK_TITLE: [bitflyergo] Test is failed
          SLACK_COLOR: danger
